#服务端口
server: 
  port: 9101

#应用名称及验证账号
spring: 
  application: 
    name: api-driver-feign
    admin:
      enabled: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000

  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1，百分之八采样
  sleuth:
    sampler:
      rate: 1  
#注册中心
eureka: 
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@eureka-7901:7901/eureka/
  instance: 
    hostname: localhost
    instance-id: api-passenger
      
    
feign:
  compression:
    request:
      mime-types:
      - text/xml
      min-request-size: 2048
  #开启feignhystrix
  hystrix:
    enabled: false  

  client: 
    config:  
      eureka-client: 
        request-interceptors:
        - com.online.taxi.feign.feign.interceptor.MyBasicAuthRequestInterceptor
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: none
        
#eureka-client: 
#  ribbon: 
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#service-valuation: 
#  ribbon: 
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients:
    - EUREKA-CLIENT


#Admin监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true
          
logging:
  level:
    org.springframework: DEBUG
    com.online.taxi.passenger.feign.ServiceForecast: debug